3D Array

In [6]:
import numpy as np

arr= [[[2,3],[3,4]],
      [[4,5],[5,7]],
        [[3,2],[1,1]]]
arr

[[[2, 3], [3, 4]], [[4, 5], [5, 7]], [[3, 2], [1, 1]]]

In [30]:
arr=np.array([[[2,3,1],[3,4,4]],
      [[4,5,3],[5,7,1]],
        [[3,2,2],[1,1,1]]])

arr

array([[[2, 3, 1],
        [3, 4, 4]],

       [[4, 5, 3],
        [5, 7, 1]],

       [[3, 2, 2],
        [1, 1, 1]]])

In [12]:
print(arr.ndim)

3


In [31]:
#indexing
# 2 - table, 1 -row, 1- coloumn , : - column indexing

arr[2,1,1:]

array([1, 1])

In [40]:
arr[0:3,0,] #choosing first rows in each table

array([[2, 3, 1],
       [4, 5, 3],
       [3, 2, 2]])

In [41]:
arr[:,0,:] #choosing first rows in each table
           #: -go to all tables

array([[2, 3, 1],
       [4, 5, 3],
       [3, 2, 2]])

In [43]:
arr = np.random.random((3,2))

In [44]:
arr.shape

(3, 2)

In [46]:
arr2 = arr.T 
arr2  #transpose

array([[0.22527625, 0.20129281, 0.85693968],
       [0.8306139 , 0.31247026, 0.51927029]])

In [47]:
arr2.shape

(2, 3)

In [51]:
arr3= np.random.random((3,2))

np.concatenate((arr3,arr))

array([[0.560691  , 0.83510455],
       [0.52552044, 0.70742756],
       [0.00823859, 0.13099596],
       [0.22527625, 0.8306139 ],
       [0.20129281, 0.31247026],
       [0.85693968, 0.51927029]])

In [53]:
np.concatenate((arr3,arr),axis=1)

array([[0.560691  , 0.83510455, 0.22527625, 0.8306139 ],
       [0.52552044, 0.70742756, 0.20129281, 0.31247026],
       [0.00823859, 0.13099596, 0.85693968, 0.51927029]])

In [55]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr+5  #5 added to everyone

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
arr.min()

0

In [58]:
arr.mean()

4.5

In [64]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,1,1],[2,2,2]])

In [62]:
arr= np.array([0,1,2])

In [63]:
a+arr

array([[1, 3, 5],
       [4, 6, 8]])

In [65]:
a+b

array([[2, 3, 4],
       [6, 7, 8]])

In [67]:
arr.sort()
arr

array([0, 1, 2])

In [69]:
a.sort()
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr.argsort()

#tells position to arrange  the array in ascending order

array([0, 1, 2], dtype=int64)

In [71]:
arr.argmin()

0